Exclude constructors in TraceMethodInstrumentation (#412)
because Byte Buddy complains about catching exceptions in constructors:
java.lang.IllegalStateException: Cannot catch exception during constructor call