Exclude constructors in TraceMethodInstrumentation
because Byte Buddy complains about catching exceptions in constructors:
java.lang.IllegalStateException: Cannot catch exception during constructor call