Fix wrong logger causing NoClassDefFoundError when using OTel bridge (#2596)
* Fix wrong logger causing NoClassDefFoundError when using OTel bridge

* add 2596 to changelog

* Fix wrong logger in InstallationListenerImpl